# Generated by Django 2.2.1 on 2020-02-18 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('date', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('content', models.TextField(verbose_name='内容')),
                ('description', models.TextField(verbose_name='文章描述')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleblog.Author')),
                ('type', models.ManyToManyField(to='articleblog.Type')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
