# Generated by Django 2.2.1 on 2020-02-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleblog', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(default='01.jpg', upload_to='images', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
