# Generated by Django 2.2.1 on 2020-02-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleblog', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
