# Generated by Django 2.2.1 on 2020-02-22 19:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleblog', '0007_auto_20200222_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('date', models.DateField(auto_now=True, verbose_name='创建时间')),
                ('content', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('description', ckeditor.fields.RichTextField(verbose_name='文章描述')),
                ('recommend', models.IntegerField(default=0, verbose_name='推荐')),
                ('click', models.IntegerField(default=0, verbose_name='点击率')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleblog.Author')),
                ('type', models.ManyToManyField(to='articleblog.Type')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
